# Generated by Django 3.1.7 on 2021-03-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0002_auto_20210324_0839"),
    ]

    operations = [
        migrations.AddField(
            model_name="consortium",
            name="projects",
            field=models.ManyToManyField(
                help_text="Project to which this object belongs.", to="beacon.Project"
            ),
        ),
        migrations.DeleteModel(
            name="ProjectConsortium",
        ),
    ]
