# Generated by Django 3.1.7 on 2021-03-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0006_remoteside'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='frank',
            new_name='authuser',
        ),
        migrations.AddIndex(
            model_name='phenotype',
            index=models.Index(fields=['case'], name='beacon_phen_case_id_532bab_idx'),
        ),
    ]
