# Generated by Django 3.1.7 on 2021-03-31 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0007_auto_20210330_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consortium',
            name='access_limit',
        ),
        migrations.RemoveField(
            model_name='consortium',
            name='key',
        ),
        migrations.RemoveField(
            model_name='remoteside',
            name='visibility_level',
        ),
    ]
