# Generated by Django 3.1.7 on 2021-04-06 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0011_auto_20210406_0950"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="authuser",
            field=models.ForeignKey(
                help_text="Remote side to which the client belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                to="beacon.remoteside",
            ),
        ),
    ]
