# Generated by Django 3.1.7 on 2021-04-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0016_auto_20210412_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='ip_address',
            field=models.GenericIPAddressField(unpack_ipv4=True),
        ),
    ]
