# Generated by Django 3.2 on 2021-04-28 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0019_alter_logentry_user_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project to which this object belongs.', null=True, on_delete=django.db.models.deletion.CASCADE, to='beacon.project'),
        ),
        migrations.AlterField(
            model_name='consortium',
            name='projects',
            field=models.ManyToManyField(blank=True, help_text='Project to which this object belongs.', null=True, to='beacon.Project'),
        ),
        migrations.AlterField(
            model_name='consortium',
            name='visibility_level',
            field=models.IntegerField(choices=[(0, 'Level_case_index_visible'), (5, 'Level_phenotype_visible'), (10, 'Level_coarse_phenotype_visible'), (15, 'Level_allele_count_visible'), (20, 'Level_allele_count_greater_ten_visible'), (25, 'Level_exists_visible')]),
        ),
        migrations.AlterField(
            model_name='phenotype',
            name='case',
            field=models.ForeignKey(blank=True, help_text='Case to which this phenotype belongs.', null=True, on_delete=django.db.models.deletion.CASCADE, to='beacon.case'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Project title', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='remotesite',
            name='consortia',
            field=models.ManyToManyField(blank=True, help_text='Consortium to which this object belongs.', null=True, to='beacon.Consortium'),
        ),
        migrations.AlterField(
            model_name='remotesite',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='case',
            field=models.ForeignKey(blank=True, help_text='Case to which this variant belongs.', null=True, on_delete=django.db.models.deletion.CASCADE, to='beacon.case'),
        ),
    ]
