# Generated by Django 3.2 on 2021-04-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0020_auto_20210428_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consortium',
            name='visibility_level',
            field=models.IntegerField(choices=[(0, 'Level_case_index_visible'), (5, 'Level_phenotype_visible'), (10, 'Level_coarse_phenotype_visible'), (15, 'Level_variant_count_visible'), (20, 'Level_variant_count_greater_ten_visible'), (25, 'Level_exists_sample_count_visible')]),
        ),
    ]
