# Generated by Django 3.2.2 on 2021-05-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0023_alter_variant_chromosome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remotesite",
            name="consortia",
            field=models.ManyToManyField(
                blank=True,
                help_text="Consortium to which this object belongs.",
                to="beacon.Consortium",
            ),
        ),
    ]
