# Generated by Django 3.2.2 on 2021-05-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0025_alter_variant_chromosome"),
    ]

    operations = [
        migrations.AddField(
            model_name="logentry",
            name="cases",
            field=models.ManyToManyField(
                blank=True, help_text="Case with request variant.", to="beacon.Case"
            ),
        ),
        migrations.AddField(
            model_name="logentry",
            name="consortia",
            field=models.ManyToManyField(
                blank=True,
                help_text="Consortium to which this object belongs.",
                to="beacon.Consortium",
            ),
        ),
    ]
