# Generated by Django 3.2.2 on 2021-05-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0026_auto_20210512_0732"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logentry",
            name="consortia",
        ),
        migrations.AlterField(
            model_name="case",
            name="index",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="consortium",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(
                help_text="Project title", max_length=255, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="remotesite",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
