# Generated by Django 3.2.2 on 2021-05-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0027_auto_20210524_1527"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logentry",
            name="request",
        ),
        migrations.AddField(
            model_name="logentry",
            name="alternative",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="logentry",
            name="chromosome",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="logentry",
            name="end",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="logentry",
            name="endpoint",
            field=models.CharField(default="\\query", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="logentry",
            name="method",
            field=models.CharField(default="GET", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="logentry",
            name="reference",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="logentry",
            name="release",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="logentry",
            name="server_protocol",
            field=models.CharField(default="g", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="logentry",
            name="start",
            field=models.IntegerField(null=True),
        ),
    ]
