# Generated by Django 3.1.7 on 2021-04-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0008_auto_20210331_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consortium',
            name='visibility_level',
            field=models.IntegerField(),
        ),
    ]
