# Generated by Django 3.1.7 on 2021-04-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0009_auto_20210406_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='pedigree',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
